---
title: "PS270 Final Project"
author: Ruby Sandeman
description: My final project
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to climate change. One idea I have for the project is analyzing the growth of renewable energy sources in Wisconsin and it's impact on reducing carbon emissions.

Potential sources to use: Global Energy Data (BP Statistical Review), U.S. Energy Information Administration (EIA), or International Renewable Energy Agency (IRENA)

Another project idea is analyzing global temperatures to highlight the increasing trend of warm temperatures---this may be too simple.

My research question is: How does COVID19 severity differ between vaccinated and unvaccinated individuals? I hypothesize that vaccinated individuals will have lower mortality rates and be less likely to require hospitalization compared to unvaccinated individuals. This research is relevant because skepticism surrounding the efficacy of COVID-19 vaccines persists.The dataset I am using consists of COVID-19 case data from a Chicago hospital, including information on the severity of each case. The explanatory variable is vaccination status, as this is expected to influence the outcome variable, which is the severity of the COVID-19 case. Severity is measured across a spectrum that includes case occurrence, hospitalization, and death. Vaccination status is tracked by the City of Chicago, which reports weekly rates of COVID-19 cases, hospitalizations, and deaths broken down by vaccine status. The outcome variable will be measured by the rate at which individuals in the cohort are either vaccinated or unvaccinated. If my hypothesis holds true, I expect to observe a pattern where unvaccinated individuals are more likely to contract COVID-19, be hospitalized, or die from the illness. Conversely, if unvaccinated individuals are less likely to experience severe outcomes, this would disprove my hypothesis. 

